# Generated by Django 6.0.4 on 2026-04-19 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_move_resort_data(apps, schema_editor):
    Tour = apps.get_model("resorts", "Tour")
    Service = apps.get_model("resorts", "Service")
    Review = apps.get_model("resorts", "Review")
    Resort = apps.get_model("resorts", "Resort")

    # 0002 has Tour.resort FK and Service.resort FK and Review.resort FK.
    # 0003 first removes those fields; so we must run this BEFORE they are removed.
    # This function will be placed before the RemoveField operations below.

    for tour in Tour.objects.select_related("resort", "resort__region").all():
        resort = getattr(tour, "resort", None)
        if resort:
            region = getattr(resort, "region", None)
            tour.location = (
                f"{resort.name}, {region.name}" if region else resort.name
            )
            tour.difficulty_level = getattr(resort, "difficulty_level", "intermediate")
            tour.save(update_fields=["location", "difficulty_level"])

    for service in Service.objects.select_related("resort").all():
        resort = getattr(service, "resort", None)
        if not resort:
            continue
        tour = Tour.objects.filter(resort_id=resort.pk).order_by("pk").first()
        if tour is None:
            tour = Tour.objects.create(
                resort_id=resort.pk,
                title=f"Перенос: {resort.name}",
                description="",
                start_date=getattr(service, "available_from", None) or "2026-01-01",
                end_date=getattr(service, "available_to", None) or "2026-01-01",
                price=getattr(resort, "price_from", None) or "0.00",
            )
        service.tour_id = tour.pk
        service.save(update_fields=["tour_id"])

    for review in Review.objects.select_related("resort").all():
        resort = getattr(review, "resort", None)
        if not resort:
            continue
        tour = Tour.objects.filter(resort_id=resort.pk).order_by("pk").first()
        if tour is None:
            tour = Tour.objects.create(
                resort_id=resort.pk,
                title=f"Перенос: {resort.name}",
                description="",
                start_date="2026-01-01",
                end_date="2026-01-01",
                price=getattr(resort, "price_from", None) or "0.00",
            )
        review.tour_id = tour.pk
        review.save(update_fields=["tour_id"])

    # Safety: any remaining services without tour -> attach to first tour.
    fallback_tour = Tour.objects.order_by("pk").first()
    if fallback_tour:
        Service.objects.filter(tour__isnull=True).update(tour_id=fallback_tour.pk)
        Review.objects.filter(tour__isnull=True).update(tour_id=fallback_tour.pk)


def forwards_seed_data(apps, schema_editor):
    Tour = apps.get_model("resorts", "Tour")
    Service = apps.get_model("resorts", "Service")

    if Tour.objects.exists():
        return

    tours = [
        Tour(
            title="Горный тур выходного дня",
            description="2 дня активного отдыха, проживание и базовая программа.",
            location="Кавказ",
            difficulty_level="beginner",
            start_date="2026-05-02",
            end_date="2026-05-03",
            price="15990.00",
        ),
        Tour(
            title="Снежный тур 5 дней",
            description="Пятидневная программа с экскурсиями и активностями.",
            location="Шерегеш",
            difficulty_level="intermediate",
            start_date="2026-12-10",
            end_date="2026-12-14",
            price="64990.00",
        ),
        Tour(
            title="Экстрим-тур PRO",
            description="Для опытных: интенсивная программа и повышенная сложность.",
            location="Домбай",
            difficulty_level="expert",
            start_date="2026-02-05",
            end_date="2026-02-10",
            price="89990.00",
        ),
    ]
    Tour.objects.bulk_create(tours)

    # Services for first tour
    t1 = Tour.objects.order_by("pk").first()
    if t1:
        Service.objects.bulk_create(
            [
                Service(
                    tour_id=t1.pk,
                    name="Трансфер",
                    price="2500.00",
                    included_in_price=False,
                ),
                Service(
                    tour_id=t1.pk,
                    name="Аренда снаряжения",
                    price="3500.00",
                    included_in_price=False,
                ),
                Service(
                    tour_id=t1.pk,
                    name="Гид",
                    price="0.00",
                    included_in_price=True,
                ),
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0002_tours_and_booking_tour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['tour', 'price'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='resorts.tour', verbose_name='Тур'),
        ),
        migrations.AddField(
            model_name='service',
            name='included_in_price',
            field=models.BooleanField(default=False, verbose_name='Включено в стоимость тура'),
        ),
        migrations.AddField(
            model_name='service',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='resorts.tour', verbose_name='Тур'),
        ),
        migrations.AddField(
            model_name='tour',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('expert', 'Эксперт')], default='intermediate', max_length=20, verbose_name='Уровень сложности'),
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(blank=True, max_length=150, verbose_name='Локация/направление'),
        ),
        migrations.RunPython(forwards_move_resort_data, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'tour')},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='included_services',
        ),
        migrations.RemoveField(
            model_name='service',
            name='resort',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='resort',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='region',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.RemoveField(
            model_name='review',
            name='resort',
        ),
        migrations.DeleteModel(
            name='Resort',
        ),
        migrations.AlterField(
            model_name="service",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="resorts.tour",
                verbose_name="Тур",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="resorts.tour",
                verbose_name="Тур",
            ),
        ),
        migrations.RunPython(forwards_seed_data, migrations.RunPython.noop),
    ]
