# Generated by Django 6.0.4 on 2026-04-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0003_remove_resorts_keep_tours_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество человек'),
        ),
        migrations.AddField(
            model_name='tour',
            name='capacity',
            field=models.PositiveIntegerField(default=20, verbose_name='Максимальное количество человек'),
        ),
    ]
