# Generated by Django 6.0.4 on 2026-04-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0004_capacity_and_people_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого'),
        ),
    ]
